//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace РегистрантКПП.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrants
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Patronomic { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Info { get; set; }
    }
}
